### ISSUE TITLE
i want delete polygon

### ISSUE THREAD

**Issue by zhuyinjing** [Wildhoney/Leaflet.FreeDraw#102]
hey,
i want delete polygon when i click during the polygon.
and it shows error:
`Cannot set property 'x' of undefined`
what's wrong?
Thank you.

**Comment by Wildhoney** [comment]
Which version of Leaflet are you using FreeDraw with?

**Comment by zhuyinjing** [comment]
newest.
im using it .
https://rawgit.com/oeway/Leaflet.FreeDraw/master/dist/leaflet-freedraw.web.js

**Comment by zhuyinjing** [comment]
i delete `bable-polyfill`
