### ISSUE TITLE
delete polygon when dbclick the polygon

### ISSUE THREAD

**Issue by zhuyinjing** [Wildhoney/Leaflet.FreeDraw#105]
hey,when i use mouse to dbclick the polygon ,and i want to delete this polygon,but it shows error:
`leaflet-src.js:2713 Uncaught TypeError: Cannot read property '_leaflet_pos' of undefined
    at Ct (leaflet-src.js:2713)
    at n._getMapPanePos (leaflet-src.js:4308)
    at n.containerPointToLayerPoint (leaflet-src.js:3891)
    at n._fireDOMEvent (leaflet-src.js:4267)
    at n._handleDOMEvent (leaflet-src.js:4229)
    at HTMLDivElement.a (leaflet-src.js:2231)`
how should i do ? 
thanks so much!

**Comment by Wildhoney** [comment]
I'm not sure why that's occurring &ndash; although delete is with a single click.

Can you replicate the issue in [the example](https://freedraw.herokuapp.com/)?

**Comment by zhuyinjing** [comment]
hey
when i delete with a single click.
it shows nothing with my polygons.
it doesn't work!
`const tileURL = this.deepzoomServer + img + '/{z}/{x}_{y}.jpeg?random=' + Math.random()
      L.tileLayer(tileURL).addTo(this.map)
      var freeDraw = new FreeDraw({
        mode: FreeDraw.ALL,
        mergePolygons: false
      })

      this.freeDraw = freeDraw
      this.map.addLayer(this.freeDraw)`
what's wrong with my code ?
And i also use it to return the newest polygon 
`var latestPolygon = eventData.latLngs.filter(function (latLngs) {
          const json = JSON.stringify(latLngs)
          const has = !~seenPolygons.indexOf(json)
          has && seenPolygons.push(json)
          return has
        })`
I want to delete my polygon , how can i modify?
Thanks  a lot !

**Comment by Wildhoney** [comment]
Looks generally okay. Does your full code look something similar [to this](https://github.com/Wildhoney/Leaflet.FreeDraw/blob/master/example/js/default.js#L105)?

**Comment by zhuyinjing** [comment]
okay..
when i when i delete with a single click,
it doesn't work with my polygons ~
And it shows nothing in chrome console...
I use it in my code 
`mode: FreeDraw.ALL`
what's wrong ? 
By the way, i use leaflet to show deepzoom picture,not map.
Thanks so much

**Comment by zhuyinjing** [comment]
I wrote the code in it .
Can you help me to see what's wrong with my code ???
https://jsfiddle.net/ea62vtva/2/

**Comment by nawerprod** [comment]
It seems that using leaflet 1.0.2 solve this issue https://jsfiddle.net/ea62vtva/4/

**Comment by zhuyinjing** [comment]
@nawerprod 
I really thanks you so much! 
yes, it resolve.
And how to handle events when i delete the polygon?

**Comment by Wildhoney** [comment]
Handle events?

**Comment by zhuyinjing** [comment]
Emmm....I want to know the lat lng that i delete.
how to know ?

**Comment by Wildhoney** [comment]
You could read it from the polygon **before** invoking `freeDraw.remove`, since you have to know which polygon is being deleted.

Alternatively you could bind to the `freeDraw.on('markers', ...)` event and find the one in that array that's missing (meaning the one that's deleted) and take its lat/lng values from there.

**Comment by zhuyinjing** [comment]
Emmmm..
I use this code to get latest polygon .

```
var latestPolygon = eventData.latLngs.filter(function (latLngs) {
          const json = JSON.stringify(latLngs)
          const has = !~seenPolygons.indexOf(json)
          has && seenPolygons.push(json)
          return has
        })
```

And  if I  bind to the freeDraw.on('markers', ...) event and find the one in that array that's missing (meaning the one that's deleted) ,  i think it's so complicated ....
Does this plugin not provide delete events ?

**Comment by Wildhoney** [comment]
That's true &mdash; I've added an update that includes the `eventType` in the `event` object, so you can do something like:

```javascript
freeDraw.on('markers', event => {

    switch (event.eventType) {
        case 'create': // ...
        case 'remove': // ...
    }

});
```

Where `eventType` can be `create | edit | remove | clear`.

**Comment by zhuyinjing** [comment]
`console.log(event.eventType)`
it's ` undefined`
what's wrong?
I use the version is [https://rawgit.com/oeway/Leaflet.FreeDraw/master/dist/leaflet-freedraw.web.js](url)

**Comment by Wildhoney** [comment]
It looks to be caching it on their CDN.

**Comment by zhuyinjing** [comment]
ok, i see you have a commit just now.
I have a try.
thank you !

**Comment by zhuyinjing** [comment]
okay... I already use version 2.4.0.
[https://jsfiddle.net/ea62vtva/5/](url)
And i found when i create polygon , it also console.log the case 'create' and  the case 'delete' at the same time.
when i remove polygon , it return all event['latLngs'] not the polygon that i delete it.
Do you hava any easy method to return the polygon that i delete??
I think you are excellent !

**Comment by Wildhoney** [comment]
You've forgotten the `break`s in your `switch` statement so it just falls through to all cases.

It's not a perfection science because of the merging of polygons, but you the following is a starting basis for tracking the polygons:

```javascript
freeDraw.on('markers', event => {

    switch (event.eventType) {

        case 'create':

            const created = event.latLngs.map(JSON.stringify).filter(hash => {
                const includes = seen.includes(hash);
                !includes && seen.push(hash);
                return !includes;
            }).map(JSON.parse);

            console.log('created:', created);
            break;

        case 'remove':

            const removed = seen.filter(hash => {
                return !event.latLngs.map(JSON.stringify).includes(hash);
            }).map(hash => {
                const index = seen.indexOf(hash);
                const model = seen[index];
                seen.splice(index, 1);
                return JSON.parse(model);
            });

            console.log('removed:', removed);
            break;

    }

});
```

**Comment by zhuyinjing** [comment]
@Wildhoney 
Thank you for taking the afternoon to help me solve the problem.
You are a good author.
I hope there's a chance to do something for you.

**Comment by Wildhoney** [comment]
You're welcome! 👍
