### ISSUE TITLE
Setting draw bounds

### ISSUE THREAD

**Issue by roberts-g** [Wildhoney/Leaflet.FreeDraw#108]
Is it possible to set the bounds in which you can draw, instead of using the default world bounds?
Example:
Only allowing drawing to be done in London, and any attempts to draw outside are cut off.

**Comment by Wildhoney** [comment]
Nope, nothing like that, but you could just set the max bounds in Leaflet, I suppose.

**Comment by roberts-g** [comment]
I've tried setting the max bounds in leaflet, although that still lets you draw outside the wanted area.
The other approach I tried was to check if any of the vertices are outside of the bounds in the markers event, and if so, just remove the polygon that has been drawn, but I wasn't able to remove the vertices using:
```
polygons.forEach(polygon => freeDraw.remove(polygon));
```
Is this because the polygon hasn't been added to the layer yet?

**Comment by Wildhoney** [comment]
There's no reason why you shouldn't be able to remove the polygons in the markers event:

```javascript
freeDraw.all().forEach(p => freeDraw.remove(p));
```

**Comment by roberts-g** [comment]
I realised the reason it wasn't working was that I was trying to pass in coordinates to remove instead of an actual polygon. If anyone happens to want to do this in the future, this is how I have done it:
```
freeDraw.on('markers', function (event) {
    const lastElement = event.latLngs[event.latLngs.length - 1];
    if (!isInBounds(lastElement) {
        freeDraw.remove(freeDraw.all()[freeDraw.all().length - 1]);
    }
```

**Comment by Wildhoney** [comment]
Thanks for updating @roberts-g 👍
