### ISSUE TITLE
Fetch latlngs behind polygons.

### ISSUE THREAD

**Issue by ryazhang** [Wildhoney/Leaflet.FreeDraw#111]
I use leaflet to make some markers on the map.
Then draw polygons among the map, like the following pic.
![image](https://user-images.githubusercontent.com/33251407/34548139-39ada2c4-f13b-11e7-9405-ba5e9c26a31b.png)

How can I fetch latlngs of leaflet's markers? 
Could you please have a look? Thanks in advance.

**Comment by Wildhoney** [comment]
@ryazhang you should subscribe to the `markers` event:

```javascript
freeDraw.on('markers', event => {
    console.log(event.latLngs);
});
```
