### ISSUE TITLE
classname mode-none is not added to map container when mode is set to NONE

### ISSUE THREAD

**Issue by ventralnet** [Wildhoney/Leaflet.FreeDraw#116]
Go here https://jsfiddle.net/7w0a6xjf/, browse to the map container element in dev tools.  Notice mode-edit, mode-create etc etc are classes on the map container.  Draw a shape.  There is a markers listener to set the mode to NONE after the shape is drawn.   Reading the documentation it suggests the mode-none class should be added to the map container.

**Comment by Wildhoney** [comment]
Thanks @ventralnet  👍All fixed, pushed and released as `v2.8.1`.
