### ISSUE TITLE
FreeDraw 2.8.0 with Leaflet 0.7.7

### ISSUE THREAD

**Issue by frulo** [Wildhoney/Leaflet.FreeDraw#117]
Hi,
Does Leaflet.free works with Leaflet 0.7.7?

freeDraw expect that polygon.getLatLngs() returns an array of array and take the first element. In my Application I only get an array of latLngs.

Thanks

Orlando

**Comment by Wildhoney** [comment]
I've not tested the current version with `v0.7.7`. However give [`v1.2.2`](https://github.com/Wildhoney/Leaflet.FreeDraw/tree/v1.2.2) a try as that was written back when `v0.7.7` was the latest version.

**Comment by frulo** [comment]
Thanks
