### ISSUE TITLE
draw polygon when second time

### ISSUE THREAD

**Issue by zhuyinjing** [Wildhoney/Leaflet.FreeDraw#120]
hi,
i use it in my code:
```
drawpolygon (annotationTypeName, color, img, dataSetName) {
      console.log(this.freeDraw)
      const tileURL = this.deepzoomServer + img + '/{z}/{x}_{y}.jpeg?random=' + Math.random()
      L.tileLayer(tileURL).addTo(this.map)
      /* eslint-disable */
      var freeDraw = new FreeDraw({
        mode: FreeDraw.ALL,
        mergePolygons: false
      })

      this.freeDraw = freeDraw
      this.map.addLayer(this.freeDraw)
}
```
when i click brush-pencil , it calls `drawpolygon`  function
and when i click brush-pencil the twice time,
the polygon background color is deeper than the first time..
what's wrong with my code?
thanks a lot!!!
![2018-04-04 16-47-38](https://user-images.githubusercontent.com/25977997/38297890-5b63ad30-3828-11e8-9c79-b1b57322cfcb.png)
![2018-04-04 16-48-17](https://user-images.githubusercontent.com/25977997/38297892-5c86a1a4-3828-11e8-8326-013661bd93de.png)

**Comment by Wildhoney** [comment]
I think it's because you keep adding layers to your map with `this.map.addLayer(this.freeDraw)`. You need to add the layer **only** once, or remove the existing layer before adding a new one.

What is it you're trying to achieve by constantly adding layers?

**Comment by zhuyinjing** [comment]
emm..
such like the photos,
i want to click red brush-pencil to circle dogs
and click green brush-pencil to circle cats..
so  i  use add layers many times..

**Comment by zhuyinjing** [comment]
i want to change different color with line , so i use it 
```
drawpolygon (annotationTypeName, color, img, dataSetName) {
      const tileURL = this.deepzoomServer + img + '/{z}/{x}_{y}.jpeg?random=' + Math.random()
      L.tileLayer(tileURL).addTo(this.map)
      /* eslint-disable */
      var freeDraw = new FreeDraw({
        mode: FreeDraw.ALL,
        mergePolygons: false
      })

      this.freeDraw = freeDraw

      this.map.addLayer(this.freeDraw)

      this.coordinates = []
      const seenPolygons = []
      var self = this
      //  返回最新的多边形
      this.freeDraw.on('markers', function getMarkers (eventData) {
        var pathtemp = document.getElementsByTagName('path')
        for (let j = 0; j < pathtemp.length; j++) {
          if (pathtemp[j].getAttribute('class').indexOf('#') === -1) {
            if (color.indexOf('#') === -1) {
              let color2 = '#' + color
              bus.$emit('setAnnotationColor', color2)
              pathtemp[j].setAttribute('class', color2)
              pathtemp[j].setAttribute('stroke', color2)
            } else {
              pathtemp[j].setAttribute('class', color)
              pathtemp[j].setAttribute('stroke', color)
            }
          }
        }
```
Is there a better solution?
When I click on the different colors of the brush, the polygon is painted in a different color.
![2018-04-04 17-28-55](https://user-images.githubusercontent.com/25977997/38299783-aa61c1d8-382d-11e8-84e0-257d0607696f.png)

**Comment by Wildhoney** [comment]
It's not an easy one to solve, as it's going against the design of `FreeDraw`. We've had a few issues relating to [multiple instances, and different colours](https://github.com/Wildhoney/Leaflet.FreeDraw/issues?utf8=%E2%9C%93&q=is%3Aissue+colors).

**Comment by zhuyinjing** [comment]
emm…
If by changing the background color of the layers of transparent?

**Comment by Wildhoney** [comment]
With two or more FreeDraw layers you're going to run into issues, because of overlapping polygons, and click events, etc... not being passed through.

With the two or more colours with the same instance we run into issues &ndash; because two polygons of red and blue can become one polygon at any point if they overlap. If you prevent polygon merging then you can target the polygons differently in CSS.

**Comment by Wildhoney** [comment]
Probably you want a different library @zhuyinjing &ndash; it doesn't really look as though you're using FreeDraw for map related functionality. There must be better alternatives out there for circling animals. Once you've circled an animal what happens?

**Comment by zhuyinjing** [comment]
In order to make multiple clicks on the brush, the color of the fill does not deepen, I temporarily used to change the style of css.
`path {
  fill-opacity: 0 !important;
}`
This does not seem to be the best solution, but at the moment it can at least solve this problem.
