### ISSUE TITLE
How to destroy previous polygon in latest version freedraw?

### ISSUE THREAD

**Issue by hoanglethuanthien** [Wildhoney/Leaflet.FreeDraw#129]
This options seem to be remove in latest version. Can you suggest about this function?

**Comment by Wildhoney** [comment]
Sorry, please remind me how it was done in the version you're using?

IIRC there's no *good* way of removing the latest because of the polygon merging. However you could take the latest polygon [from the `all` method](https://github.com/Wildhoney/Leaflet.FreeDraw#bundled-methods) and then use the `remove` function to delete it.

**Comment by hoanglethuanthien** [comment]
Thank you so much, I solved my problem. In my task, I don't want multiple polygon, draw one polygon and search in it, then if draw another (destroy first polygon).

**Comment by Wildhoney** [comment]
Oh, okay. Yep, in that case you need to [set the options](https://github.com/Wildhoney/Leaflet.FreeDraw#passing-options) &ndash; specifically `maximumPolygons : 1` 👍

**Comment by hoanglethuanthien** [comment]
If set ```maximumPolygons  :  1```, I can not continue draw. My goal like  this (https://foursquare.com/explore?mode=url&polygon=21.040126706656%2C105.82741498947144%3B21.039565947575543%2C105.82799434661864%3B21.03900518638399%2C105.82823038101196%3B21.038264177285843%2C105.82825183868408%3B21.03752316450155%2C105.82769393920897%3B21.03704250558948%2C105.82694292068481%3B21.03684223058507%2C105.82593441009521%3B21.036922340619142%2C105.824453830719%3B21.037603274169452%2C105.82316637039185%3B21.037983794503656%2C105.82286596298218%3B21.03840436847903%2C105.82273721694945%3B21.038985159159534%2C105.82286596298218%3B21.039866354488336%2C105.82385301589966%3B21.0403069501978%2C105.82509756088257%3B21.040387058368605%2C105.82679271697998%3B21.040126706656%2C105.82741498947144)

**Comment by Wildhoney** [comment]
Ah I see. All good now?

**Comment by hoanglethuanthien** [comment]
I thinks it fine until testers work :heart_eyes:

**Comment by Wildhoney** [comment]
Haha. Familiar story!
