### ISSUE TITLE
Demo is down

### ISSUE THREAD

**Issue by hno2** [Wildhoney/Leaflet.FreeDraw#131]
The Demo under https://freedraw.herokuapp.com/ seems to be down. I only get an Application error.

**Comment by lmdc45** [comment]
Same for me

**Comment by Wildhoney** [comment]
Sorry folks &mdash; my mistake! [I've brought it back](https://freedraw.herokuapp.com/) now. Thanks.

**Comment by lmdc45** [comment]
Thanks
