### ISSUE TITLE
webpack go wrong

### ISSUE THREAD

**Issue by DaHuLuBa** [Wildhoney/Leaflet.FreeDraw#132]
![image](https://user-images.githubusercontent.com/32380005/56714235-c91da880-6766-11e9-825e-802b4868e5c5.png)

I started reporting errors when I started the project

**Comment by will4906** [comment]
I have the same problem!!!

**Comment by Wildhoney** [comment]
You need to be using the web version, not the CJS version. I've [just added](https://github.com/Wildhoney/Leaflet.FreeDraw/commit/f5c8f8c3bf97b449effb1bd33b51a08f4291f517) the `browser` key to the `package.json` file, so hopefully that should pick up the right one for you.

**Comment by ankeetmaini** [comment]
The latest code isn't published to npm. Also the web version will attach itself as a global object. Can't use it in ES6 imports. Please see #133
