### ISSUE TITLE
Demo not working

### ISSUE THREAD

**Issue by myulz** [Wildhoney/Leaflet.FreeDraw#136]
The jsfiddle in the readme is not working, I think because this file is no longer available:
https://rawgit.com/Wildhoney/Leaflet.FreeDraw/master/dist/leaflet-freedraw.web.js

**Comment by Wildhoney** [comment]
Thanks! Good spot. All working now: https://jsfiddle.net/0dzhs5Lg/3/

**Comment by Wildhoney** [comment]
Probably should re-remove the `dist/` files from the repo, and use CodeSandbox for the demo though. For another day.
