### ISSUE TITLE
ES6 Import trouble

### ISSUE THREAD

**Issue by stell** [Wildhoney/Leaflet.FreeDraw#163]
When installing via node or yarn i only get the dist folder.  I need to integrate this as an ES6 import and let it transpile via buble.

ATM this is not possible and the dist code makes trouble in IE 11 because i can't transpile it. I get an error around the `toStringTag`  Symbol.

This is a great library, but let us use it in ES6 imports.

**Comment by Wildhoney** [comment]
We don't have a `.npmignore` file so you should be getting the `src` directory as well. I've tested this myself and get almost all the files that the repo has.

`import react-shadow/src` not work for you, if you're after the uncompiled file?

**Comment by stell** [comment]
Thanks for answering. Don't know what's going wrong.  Using npm or yarn makes no difference.
`yarn add leaflet-freedraw` only creates the dist folder. `src `folder is missing.

**Comment by stell** [comment]
Could you please check your package.json? Looks like this is preventing to get the /src Folder:
{
  "files": [
    "dist"
  ],
}

**Comment by Wildhoney** [comment]
Sorry, I totally forgot about this issue @stell. Resolved with `leaflet-freedraw@2.13.2`.

**Comment by stell** [comment]
Thank you. Problem solved.
