### ISSUE TITLE
Draw Layer Problem

### ISSUE THREAD

**Issue by ealoticopve** [Wildhoney/Leaflet.FreeDraw#164]
Hello my friend,

I am very interested in your plugin and have already managed to integrate it into my application, however, it is not working well with other plugins.

Note that when I use the tool to draw more than 1 time, the rest of my code stops working. When I say this, what I mean is that it creates a kind of layer, and leaves all other objects instantiated on the map without interaction, I can't click them. I think there has to be something with the Z-index or the drawing is occupying a much higher layer than the one that appears on the map.
![1](https://user-images.githubusercontent.com/61938096/80598873-e3e1c780-8a21-11ea-9471-8bed7b49d99f.JPG)
![2](https://user-images.githubusercontent.com/61938096/80598877-e47a5e00-8a21-11ea-8259-496514b80d24.JPG)

- In the first image I can click the circle and get a popup and information from the click. (Before drawing)
- In the second image, I can't click the circle and get its information (After more than 1 drawing)

PS: As I mentioned, with 1 drawing it works, with more than 1 it doesn't.
Hope you can help me, thank you!

**Comment by Wildhoney** [comment]
Could you please use https://jsfiddle.net/0dzhs5Lg/3/ to create a quick example?

**Comment by ealoticopve** [comment]
Hello! Here is the example (part of my code)
https://jsfiddle.net/1nrfbkd6/2/

**Comment by ealoticopve** [comment]
Please, let me know if you see the example. Thank you!

**Comment by Wildhoney** [comment]
Thanks, yep. I see the issue in the JSFiddle, but when I added your code to the example from this repo, it seems to work fine. I can always click on the marker. I can't seem to find the difference between the two which is frustrating.

**Comment by ealoticopve** [comment]
What can it be then? I've tried everything, including uninstalling and installing the npm plugin

**Comment by ealoticopve** [comment]
My friend, I came to the conclusion that the problem is not free draw. Sorry for this inconvenience. I'm using the [SemiCircles plugin](https://github.com/jieter/Leaflet-semicircle) and it doesn't work with yours and probably others. I tested both separately and that's what I deduced. Your work is fantastic, and thanks for the replies.

**Comment by Wildhoney** [comment]
Ah! That's probably why I found it difficult to reproduce locally. Glad you've found it &ndash; please let me know if I can help further once you identify the actual issue with that plugin.

**Comment by ealoticopve** [comment]
Thank you for your disposition !! I'll keep the topic open. If you find a solution I will leave it here. Thank you!

**Comment by ealoticopve** [comment]
Hello again, sorry to bother you! But I was wondering if there is any way to know if the user drew it.
To solve the problem, I'm deleting the circles and instantiating again. But I would only like to do it when the user finishes the drawing.

https://jsfiddle.net/d3w2mqp4/1/

**Comment by Wildhoney** [comment]
Yep, you can use:

```javascript
freeDraw.on('markers', event => {
    console.log('Added, remove or edited polygons!');
});

**Comment by ealoticopve** [comment]
Good Morning! Thank you very much, I completely forgot about this event! **Everything is working as intended** , 1000 thanks! I'll close the post.
