### ISSUE TITLE
[SOLVED] ModuleNotFoundError: No module named 'demos'

### ISSUE THREAD

**Issue by Isaamarod** [Wildhoney/Leaflet.FreeDraw#169]
If you try to execute : python usage-elements-extra.py  it launchs an error like:

```
  File "usage-elements-extra.py", line 10, in <module>
    from demos import dash_reusable_components as drc
ModuleNotFoundError: No module named 'demos'
```

You can solve if delete in line 10:  from demos

**Comment by Wildhoney** [comment]
Wrong repo?

**Comment by Isaamarod** [comment]
dash_reusable_components belongs to demo..

**Comment by Wildhoney** [comment]
Freedraw is a JavaScript module, there’s no Python?

**Comment by Isaamarod** [comment]
Yes, I apologize. This issue belongs to other repo. Is it possible to delete it? Thanks.
