### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'x')

### ISSUE THREAD

**Issue by gmarshall56** [Wildhoney/Leaflet.FreeDraw#184]
I am using this Leaflet.FreeDraw library in a React application.  This is what I have coded:
`
import leaflet-freedraw/dist/leaflet-freedraw.iife;
...
    const freeDraw = new FreeDraw();

    const toggleFreeDraw = () => {
        if(freeDrawEnabled){
            geomanIsDrawing.current= false;
            freeDraw.mode(FreeDraw.NONE);
        }else{
            geomanIsDrawing.current= true;
            freeDraw.mode(FreeDraw.CREATE | FreeDraw.EDIT | FreeDraw.DELETE);
        }
        freeDrawEnabled = !freeDrawEnabled;
    }

    map.addLayer(freeDraw);
    freeDraw.mode(FreeDraw.NONE);
    map.pm.Toolbar.createCustomControl(
    {name: 'myFreeDrawer2',
        block: 'draw',
        title: 'Draw Freehand Polygons',
        onClick: toggleFreeDraw,
        className: 'icon-freedraw'
        });
`

When I finish drawing a freehand polygon on my map I get this error:

![leafletFreeDrawError](https://user-images.githubusercontent.com/5943189/132526031-de5a10bf-7991-4828-9093-692fea099c65.JPG)

Can you please advise?
Thank you for your time.

**Comment by gmarshall56** [comment]
Never mind.. I think I figured this one out...

**Comment by MaciejGL** [comment]
Could You describe what was the problem and how did you solve it? Thanks

**Comment by ccxh505398633** [comment]
我也碰到一样的问题，使用已下方式解决，在leaflet创建实例时设置属性preferCanvas为false
