### ISSUE TITLE
Programmatically set a polygon

### ISSUE THREAD

**Issue by hotmeteor** [Wildhoney/Leaflet.FreeDraw#26]
Is there a way to programmatically set a polygon on page load? I've tried the following, to no avail:

```
var freeDraw = new L.FreeDraw({
    multiplePolygons: false,
    mode: L.FreeDraw.MODES.VIEW
});
var polygon = L.polygon([latLngs]);
freeDraw.addLayer(polygon);
```

**Comment by GabrielCW** [comment]
@hotmeteor May I ask exactly how you solved that problem?

I'm facing the same issue right now, and I can imagine others might too in the future.

**Comment by Wildhoney** [comment]
[`createPolygon`](https://github.com/Wildhoney/Leaflet.FreeDraw/blob/master/components/FreeDraw.js#L739-L838) should do it for you.

**Comment by hotmeteor** [comment]
I don't totally remember, and it's in a codebase I no longer have access to. However, I think all that I did was add the polygon layer to the map instead of FreeDraw, something like:

```js
map.addLayer(polygon);
```

**Comment by GabrielCW** [comment]
``createPolygon``  worked like a charm, thanks!
