### ISSUE TITLE
Add 'cut' to enable selective removal of area from polygon [enhancement]

### ISSUE THREAD

**Issue by tomsutton1984** [Wildhoney/Leaflet.FreeDraw#28]
Enables donut polygons

**Comment by petoor** [comment]
I am facing the same issue, is this possible as of 2019?

**Comment by skydiablo** [comment]
https://gis.stackexchange.com/questions/329817/cutting-holes-in-custom-polygon-made-with-leaflet-draw

One possibility of doing this would be with the help of turf.js library.

When adding newly drawn polygon, algorithm for detecting and creating possible holes goes like this:

1. Convert newly created layer/polygon to GeoJSON and then to turf geometry.
2. Iterate through all existing layers/polygons.
3. Convert each layer/polygon to turf geometry and check if it contains newly created polygon.
4. If it contains newly created polygon, drill hole in it with with turf.difference method
5. Remove old polygon without one hole.
6. Add new polygon.

Here is the code:

```JS
map.on('draw:created', function (e) {
  var geojson;
  var geom;
  var newGeom;
  var newLayer;

  var newLayer = e.layer;
  var newGeom = turf.getGeom(newLayer.toGeoJSON());

  drawnItems.eachLayer(function (layer) {
    geojson = layer.toGeoJSON();
    if (geojson.type == 'FeatureCollection') {
      geojson = geojson.features[0];
    }
    geom = turf.getGeom(geojson);
    if (turf.booleanContains(geom, newGeom)) {
      newGeom = turf.difference(geom, newGeom);
      newLayer = L.geoJSON(newGeom);
      drawnItems.removeLayer(layer);
    }
  });
  drawnItems.addLayer(newLayer);
});
```
