### ISSUE TITLE
Draw polylines?

### ISSUE THREAD

**Issue by Jakobud** [Wildhoney/Leaflet.FreeDraw#37]
Is it possible to draw polylines instead of polygons? Allowing people to essentially write words and draw pictures on the map?

**Comment by carpiediem** [comment]
Is there any plugin similar to this one that would allow me to drag my mouse along a path an have the plugin programatically figure out the best nodes to use for a good-match polyline?  That's the use case I'm after, drawing paths that look natural without manually placing every node.

**Comment by Jakobud** [comment]
I've looked for the same thing @carpiediem but found none.

**Comment by Wildhoney** [comment]
What would you folks use that for?

**Comment by carpiediem** [comment]
To draw the path someone took across a map (when it doesn't follow roads).

**Comment by Wildhoney** [comment]
Ah! Well it should be easier than a freehand polygon, so I might give it a try. Although it will be a different module to this. I suppose like this, you could add and remove elbows?

**Comment by carpiediem** [comment]
Adding/removing elbows would be helpful, but less critical than making the polyline easy to draw in the first place.  Whether its bundled in this plugin or packaged on its own is no matter to me; I'm just not quite skilled enough to make the changes myself.

**Comment by Jakobud** [comment]
Its out of the scope of this plugin.

**Comment by Wildhoney** [comment]
Agreed. Will be a different module.

**Comment by Wildhoney** [comment]
I've [made a start](https://github.com/Wildhoney/L.Pather) with the polyline module with an example up on Heroku: [pather.herokuapp.com](http://pather.herokuapp.com/). Although it works, it's still very much work in progress :+1:

**Comment by Jakobud** [comment]
That is really nice @Wildhoney. I was thinking about doing the same thing sometime. Is it possible to alter the accuracy of the polyline? Essentially change the number of segments created for a curve?

**Comment by Wildhoney** [comment]
Thanks @Jakobud. Yep, there's the range slider in the top left for the tolerance. Pull requests welcome! I can also make you a contributor.
