### ISSUE TITLE
Drawing a polygon in IE11 does not work.

### ISSUE THREAD

**Issue by Thomas-Persson** [Wildhoney/Leaflet.FreeDraw#38]
This seems not to be the case in all IE11 minor versions but at least in version 11.0.9600.17351  (update version is 11.0.13 KB2987107). Does not work in my project and does not work on the example app on freedraw.herokuapp.com. I have tried on different computers and get the same result. The problem is in _attachMouseDown, where it tries to bind mousedown and touchstart, this.map.on('mousedown touchstart', function onMouseDown(event).

The callback never gets triggered even though onMouseMove does. Even though I replace mousedown and touchstart with click, the callback never gets triggered. If I change IE emulator to use IE9 it works properly.

**Comment by MarkAPhillips** [comment]
Hi - this will be an issue with touch screen devices that run under Windows 8.x and IE. On non-touch screen devices this should work as expected. I think its the way that Leaflet handles this.
I have seen similar leaflet plugins have issues with this also - but not seen it resolved yet.

if you disable the touch screen on your notebook see http://lifehacker.com/disable-your-laptop-s-touch-screen-in-windows-8-1-1588333600

it will work as expected. 
I am not sure of a workaround for this but would be interested to see one.

**Comment by Wildhoney** [comment]
@MarkAPhillips, Thanks for this! :+1: Is there an active issue on Leaflet for this?

**Comment by MarkAPhillips** [comment]
Not sure - see this thread on another plugin which has similar issues:

https://github.com/Leaflet/Leaflet.draw/issues/2
I think they are working on a fix for it - but it might give you an insight where they are going with a fix.

also
https://github.com/Leaflet/Leaflet.draw/issues/273

**Comment by Wildhoney** [comment]
hull algorithm
