### ISSUE TITLE
Exiting a mode re-enables disabled map options

### ISSUE THREAD

**Issue by chriserickson** [Wildhoney/Leaflet.FreeDraw#39]
I have the scrollwheel disabled on a non-fullscreen map. 

When Free-draw exits create mode, it re-enables the scroll wheel. This is unexpected and rather annoying.

**Comment by Wildhoney** [comment]
Any luck with this?

**Comment by chriserickson** [comment]
Yeah, it appears fixed. Thanks!

----------------
chris erickson
801.613.0450
"No man knows how bad he is till he has tried very hard to be good. "

**Comment by Wildhoney** [comment]
You're welcome! :beers:
