### ISSUE TITLE
Add Holes to Polygon 

### ISSUE THREAD

**Issue by dfliess** [Wildhoney/Leaflet.FreeDraw#43]
createPolygon method is not accepting  polygons with a Region and holes. http://leafletjs.com/reference.html#polygon says "You can also create a polygon with holes by passing an array of arrays of latlngs, with the first latlngs array representing the exterior ring while the remaining represent the holes inside."

**Comment by Wildhoney** [comment]
Unfortunately with the concave hull algorithm the holes are automatically filled in &ndash; to introduce the feature of allowing holes in the polygon, we'd need to have a rethink.

What's your use-case for this?
