### ISSUE TITLE
Canvas support

### ISSUE THREAD

**Issue by timjk** [Wildhoney/Leaflet.FreeDraw#44]
FreeDraw doesn't display polygons when leaflet is set to canvas rendering.

Fiddle: http://jsfiddle.net/2u3wt2kc/4/

It seems that leaflet will support both svg and canvas rendering simultaneously in the next release so a fix may not be necessary: https://github.com/Leaflet/Leaflet/issues/3098

**Comment by Wildhoney** [comment]
Thanks @timjk! Agreed that maybe it's a good idea to wait for the next release of Leaflet. Although I'll take a quick look to see if there are any obvious issues.

**Comment by bozdoz** [comment]
There are two issues here (assuming `L_PREFER_CANVAS = true`): 

1. `setPathClipperPadding` alters `L.Path.CLIP_PADDING` which in my tests completely clips each  polygon, rendering it invisible
2. `emitPolygonCount` is looking for svg paths which won't exist, determining that there are no polygons and then calling `_clearPolygons` (which removes the canvas polygons)

I can submit a proposed fix.
