### ISSUE TITLE
Add callback function to handle the created and edited polygon

### ISSUE THREAD

**Issue by calvin1978** [Wildhoney/Leaflet.FreeDraw#46]
'markers' event only return all markers, but i wish to get the created polygon after drew it.
Now i just modify the _createMouseUp() to add the callback function, can you support it officially?

The edit mode is more difficult when multiple polygon in the map, we need to tell the callback function which polygon had been edited.

**Comment by Wildhoney** [comment]
What did you change the `_createMouseUp` method to?

This is not something that `FreeDraw` necessarily needs to implement. Assuming you've already solved the problem of which markers to remove for the delta, you could simply store the previous set of lat/lngs and then compute a diff on the new set of lat/lngs &ndash; that will give you the modified polygons.

Using [Lodash](https://lodash.com/), for example:

```javascript
var previous = [[[1,1], [1,1]], [[2,2], [2,2]], [[3,3], [3,3]], [[4,4], [4,4]]],
    current  = [[[1,1], [1,1]], [[2,2], [0,0]], [[3,3], [3,3]], [[0,0], [4,4]]];

var indexes = _.map(previous, function(d, i) {
    return (_.xor(_.flatten(d), _.flatten(current[i])).length !== 0) ? i : null;
}).filter(function(d) { return d; });

console.log('Modified Groups: ' + indexes.join(', '));
```
