### ISSUE TITLE
Option destroyPreviousPolygon is not working

### ISSUE THREAD

**Issue by immccc** [Wildhoney/Leaflet.FreeDraw#47]
Don't know if it is a navigator issue (i'm using JavaFX WebEngine navigator embedded in an app), but option destroyPreviousPolygon is not working. By debugging, i realized that, in function createPolygon(latLngs, forceCreation),:

```
    /**
     * @method createPolygon
     * @param latLngs {L.LatLng[]}
     * @param [forceCreation=false] {Boolean}
     * @return {L.Polygon|Boolean}
     */
    createPolygon: function createPolygon(latLngs, forceCreation) {

        if (!this.options.multiplePolygons && this.getPolygons(true).length >= 1) {

            if (this.options.destroyPrevious) {

                // Destroy the current polygon and then draw the current polygon.
                this.silently(this.clearPolygons);
```

this.getPolygons(true).length is always returning 0. Behaviour is the expected one if I replace that by this.polygons.length

**Comment by Wildhoney** [comment]
It could be your environment &ndash; is it possible for you to try this somehow else?

Also bear in mind that the `destroyPreviousPolygon` method is to be used in conjunction with the `allowMultiplePolygons` method, otherwise it has no effect.

```javascript
freeDraw.options.destroyPreviousPolygon(true);
freeDraw.options.allowMultiplePolygons(false);
```

**Comment by immccc** [comment]
I set both options and, by debugging, they are indeed true and false, respectively. 

Also, I tried to manually remove old polygons after creation, but I realized as well that altering polygon array doesn't guarantee the expected order in the execution time, as it might happen that selected polygons to be deleted are not the ones you want (all of them but the one in polygons.length - 1)

**Comment by Wildhoney** [comment]
I've just tested it myself in Chrome and it seems perfectly fine. I'm unsure about JavaFX WebEngine navigator, because I've never used that before, and I'm not sure on the consequences of using that.

**Comment by immccc** [comment]
I did and worked out on Chrome. It is also that can be done by uncommenting the option setting lines in the sample test.

I guess it's a tricky compatibility issue. Oracle says modern web standards are compliant, but there is always something that could be skipped.

http://docs.oracle.com/javafx/2/webview/jfxpub-webview.htm
