### ISSUE TITLE
After drawing an invalid polygon (vertical line), scroll zoom no longer works until a valid polygon is created

### ISSUE THREAD

**Issue by chriserickson** [Wildhoney/Leaflet.FreeDraw#51]
I verified on the demo heroku app --

Before you draw anything, mouse scroll wheel zooms in/out
Draw a vertical line which results in no free-draw polygon
Mouse scroll wheel zoom now zooms body
Draw a valid polygon
Mouse scroll wheel zoom  now zooms in/out again

**Comment by Wildhoney** [comment]
Good spot! Please verify the fix with `v1.1.10` :+1:

**Comment by Wildhoney** [comment]
Please try with [`v2.0.0`](https://github.com/Wildhoney/Leaflet.FreeDraw).
