### ISSUE TITLE
Multiple FreeDraw instances

### ISSUE THREAD

**Issue by jekuno** [Wildhoney/Leaflet.FreeDraw#53]
_The problem_: How to setup multiple FreeDraw instances to draw polygons in several colors (having a toolbar with e.g. buttons blue and pink to draw blue or pink FreeDraw polygons)

_The basics_: I know how to configure the according color of the drawing line, polygon stroke and polygon fill if I use only ONE freedraw control (and I know how to connect it to a button).

_Get it working for several polygon colors_:
- I created several FreeDraw instances and connected each of them to a button
- I used the method `setIconClassName` to configure the elbow colors separately.
- I then added an option which allows to configure the class name provided in https://github.com/Wildhoney/Leaflet.FreeDraw/blob/master/dist/leaflet.freedraw-src.js#L205
  - This allows me to define stroke and fill color for the several polygon types separately (should this option maybe be added to `Leaflet.FreeDraw` in general?)

_What works_
I can then click the blue button and draw a blue polygon with blue elbows.
Afterwards I click the pink button to draw a pink polygon with pink elbows.

_The problem_
The second polygon draws as expected BUT the elbow colors of the first polygon change from blue to pink as well. The first polygon needs to stay blue of course.

I already debugged everything again and again but didn't find the reason for that.
I suppose that the elbows are somehow stored in a global context (maybe at the map directly?)
but I don't know where and how to fix it.

Do you have any idea? Thanks in advance!

**Comment by Wildhoney** [comment]
@jekuno an interesting use! Could you setup a JsFiddle using http://jsfiddle.net/jrnt69xn/ please.

**Comment by jekuno** [comment]
@Wildhoney Thanks for your fast answer. I created a fiddle: http://jsfiddle.net/1smuagqz/2/

Reproduce the problem: Press the upper button on the left to switch to yellow mode. Draw a polygon. Press the other button to switch to pink. Draw a polygon. You see the changing elbow colors as described. 

(In the fiddle the fill color also still is the same for all polygons but I solved this already as described above).

**Comment by jekuno** [comment]
@Wildhoney Could you already have a look at the fiddle? :)

**Comment by Wildhoney** [comment]
Please take a look at `v1.1.11` @jekuno &ndash; I've added support for multiple class names, as I'm not fond of the consequences of having multiple instances of the `FreeDraw` layer &ndash; mostly because the binding of events are done on the map instance, rather than on a layer instance (which seems like a Leaflet limitation, but c'est la vie).

```javascript
freeDraw.options.setIconClassName(['edge-first', 'edge-second']);
freeDraw.options.setPolygonClassName(['polygon-first', 'polygon-second']);
```

You can probably guess, but by supplying an array of class names to the associated methods, the class names will be set depending on the index of the polygon &ndash; and the edges associated with the polygon.

There is a problem in that if you define only two class names, and you add three polygons, then the third polygon will have zero custom class names.

How would you expect this to be solved? Would it cycle through the class names again once it reaches the end, or would you instead expect it to assume a default. Perhaps something like:

```javascript
freeDraw.options.setPolygonClassName(['polygon-first', 'polygon-second'], 'polygon-default');
```

**Comment by jekuno** [comment]
Thanks for investigating this. I had a look at it and I'm afraid it doesn't meet my needs yet:

The user wants to draw none, one or many polygons of the same color e.g. two blue polygons, no pink polygon and seven brown polygons. He has buttons to switch to the desired color so that he can e.g. start with drawing two brown polygons, then add a blue polygon, then continue drawing brown polygons.

You suggest to use only _one_ instance of the `FreeDraw` layer. I'm fine with this.
I can think of the following solution:

Allow to provide hashes for setting the class names such as:
`setIconClassName({"land": "myBrownIconClass", "water": "myBlueIconClass"})`
`setPolygonClassName({"land": "myBrownPolygonClass", "water": "myBluePolygonClass"})`

Add a function such as `setCurrentType(type)`. If the user clicks the blue
button we could then invoke `setCurrentType('water')` to set the type to 'water' and use the blue css
classes for icon and polygon.

Finally there only needs a way to attach events for each type
(e.g. to handle the addition of a new `water` polygon) and to get the polygons by type (e.g. in order to
persist them separately).

What do you think?

**Comment by Wildhoney** [comment]
It seems very specialised, but I'm happy to look into it :+1: Give me some time please.

**Comment by jekuno** [comment]
Great news. Thanks for this! I'm curious what you will end up with :)

**Comment by jekuno** [comment]
@Wildhoney Out of curiosity... Did you already find some time to look into it? :)

**Comment by jekuno** [comment]
@Wildhoney Any news on this already? If I can assist on this feel free to leave a note! :)

**Comment by jekuno** [comment]
@Wildhoney In https://github.com/Wildhoney/Leaflet.FreeDraw/issues/53#issuecomment-99896674 you planned to look into the 'Multiple FreeDraw instances' feature.
I will need to get this feature working soon - are you still after it? If not so, can you give me some ideas on how to implement it myself?
Thanks a lot!
