### ISSUE TITLE
Polygon is reset when using leaflet developmen version

### ISSUE THREAD

**Issue by melmeseery** [Wildhoney/Leaflet.FreeDraw#56]
I have a project that requires working on Leaflet development version (0.8 - 1.0),  I already implemented some features that uses the development version of the code.  I wanted to use freedraw in the project. The code is not compatible with the new version, I have tried both the 0.8 and 1.0 and both does not work. It works find with the 0.73 leaflet but I need it to work with the new version. 

 The problem is the with the new development version the any polygon the user draw are reset immediately  and the **event.latLngs**  is always empty array.  The code clearly add the polygon then it disappears again and the final is empty event data. 
 I have tried to debug the code for a little is seems that the polygon is added to the layer in _createPolyon_ but the following code result will clear all the polgyon as it does not reterive any layer with the freedraw polygons.  The first thing I noticed is the GROUP_TAG in the development version will have to be "SVG" I changed that but still the layer is not detected and the polygon is not added to the _polygons_ array. 

The following code _getPolygon_
'''

```
            var GROUP_TAG = 'G';
            for (var layerIndex in this.map._layers) {
                if (this.map._layers.hasOwnProperty(layerIndex)) {
                    var polygon = this.map._layers[layerIndex]; 
                    // Ensure we're dealing with a <g> node that was created by FreeDraw (...an SVG group element).
                    if (polygon._container && polygon._container.tagName.toUpperCase() === GROUP_TAG) {
                        if (polygon instanceof L.FreeDraw.Polygon) {
                            polygons.push(polygon);
                        }
                    }

                }

            }

        } 
```

'''

Could any one just help on how to solve this. ?  what to fix to make it work.

**Comment by Wildhoney** [comment]
Please try with [`v2.0.0`](https://github.com/Wildhoney/Leaflet.FreeDraw).
