### ISSUE TITLE
CREATE mode disables scroll wheel zooming and never enables it again

### ISSUE THREAD

**Issue by fplgusmao** [Wildhoney/Leaflet.FreeDraw#57]
I have first noticed this in my app but even in the provided heroku app you can see the problem.

In the example app, as expected, when in the `CREATE` mode, the "scroll to zoom" is deactivated. There, after drawing a polygon (since `freeDraw.options.exitModeAfterCreate` is on), `CREATE` mode becomes disabled, and, with it, the "scroll to zoom" becomes enabled again. So far, so good. **The problem is when**, in `CREATE` mode, you change to some other mode "manually" – in this case, for example, by clicking on some other mode's "only" link before drawing something. Then, the zoom never becomes enabled again.

I suspect that only the "automatic mode switch", like when `freeDraw.options.exitModeAfterCreate` is active, is calling the correct function to set the `defaultPreferences` back again. I tried to look into the code, but I got kinda lost... If you can't find the time to try to debug this, you could give me some basic directions and I could try to look deeper into it.

**Comment by stev-0** [comment]
I don't know if this really is this simple. It seems to work on my limited testing, but I'm assuming there was a good reason for having it in the condition originally. You could try the patch anyway

**Comment by fplgusmao** [comment]
@stev-0 sorry for the ignore, man, I just saw your answer now! meanwhile I'm refactoring my whole app, and I will just take care of the FreeDraw part after a while... When I do it, I'll try your patch and see if it works.

Thanks very much!

**Comment by fplgusmao** [comment]
@stev-0 Only tried this now, but it's working perfectly, for me! would be great to hear from @Wildhoney to know if this can be merged.

**Comment by Wildhoney** [comment]
Happy to merge, folks! @stev-0 Would you like to open a PR for this, please?
