### ISSUE TITLE
mobile issues

### ISSUE THREAD

**Issue by tharrington** [Wildhoney/Leaflet.FreeDraw#59]
I am able to use the free draw in the browser, but when I run in the iOS simulator (as a cordova/ionic app), the drawing does not work. Is this compatible?

**Comment by Wildhoney** [comment]
There's been quite a few on-going discussions about supporting mobile, but Leaflet doesn't currently provide the necessary hooks to make it mobile-friendly. It is possible to support it &ndash; but needs some thought.

See https://github.com/Wildhoney/Leaflet.FreeDraw/issues/3
