### ISSUE TITLE
browserify support

### ISSUE THREAD

**Issue by mathisonian** [Wildhoney/Leaflet.FreeDraw#62]
Hey @Wildhoney, 

Thanks for the awesome library. We've been using it happily for the [lightning-viz](http://lightning-viz.org) project.

Unfortunately because we are using browserify instead of script tags, we are running into some issues and have had to fork it to get it to work properly https://github.com/mathisonian/leaflet.freedraw-browserify, but obviously this is not ideal (makes it hard to upgrade, etc, etc. see mathisonian/leaflet.freedraw-browserify#1 as an example).

The leaflet plugin [development guide](https://github.com/Leaflet/Leaflet/blob/master/PLUGIN-GUIDE.md) has a section on the best way to make plugins compatible with module loaders. Would you be willing to update (or I'm happy to submit a PR) switching to those conventions?

cc @biovisualize

**Comment by Wildhoney** [comment]
Absolutely @mathisonian &mdash; if you could open a PR based on Leaflet's outlined best practices as you mentioned, that would be awesome :+1: Happy to merge.

**Comment by mathisonian** [comment]
awesome, I should have some time to put together a PR over the next couple of days

**Comment by Wildhoney** [comment]
Thanks @mathisonian! Good work.

**Comment by freeman-lab** [comment]
:+1: this will be really useful!

**Comment by njbarrett** [comment]
@mathisonian did you manage to get a PR together? Im interested in using it

**Comment by Wildhoney** [comment]
Please try with [`v2.0.0`](https://github.com/Wildhoney/Leaflet.FreeDraw).
