### ISSUE TITLE
leaflet.draw and events subscription

### ISSUE THREAD

**Issue by gherardovarando** [Wildhoney/Leaflet.FreeDraw#66]
Thanks for the plugin,
It is possible to use it in conjunction with leaflet.draw ? I tried but  freeDraw seems to broke some of leaflet draw capabilities.
Moreover I do not get how to subscribe to featureGroup events like "layeradd" ? It seems that using freeDraw.on("layeradd",...) does not work. 
Thanks

**Comment by Wildhoney** [comment]
People have had [some luck](https://github.com/Wildhoney/Leaflet.FreeDraw/issues/24) in toggling between the two by disabling one or the other.

For the `layeradd` event I don't see any reason why it wouldn't work, assuming your adding a layer to FreeDraw. For the map itself use the `layeradd` event on `L.Map` instance.
