### ISSUE TITLE
Is it possible to remove D3.js as a dependency? 

### ISSUE THREAD

**Issue by VictorChen** [Wildhoney/Leaflet.FreeDraw#69]
D3 is a pretty big library, is it possible to achieve the same result without it?

**Comment by Wildhoney** [comment]
Absolutely! I've been thinking the same. Will take a look into it, unless you want to attempt it yourself!

**Comment by Wildhoney** [comment]
Will try to achieve this when I upgrade to 1.0 in https://github.com/Wildhoney/Leaflet.FreeDraw/issues/76
