### ISSUE TITLE
How to change draw path color?

### ISSUE THREAD

**Issue by VictorChen** [Wildhoney/Leaflet.FreeDraw#70]
Seems like it's currently hardcoded to `#D7217E` ?

**Comment by Wildhoney** [comment]
Yes, but just [overwrite it](https://github.com/Wildhoney/Leaflet.FreeDraw/blob/master/example/css/Map.css#L27-L29) with your own CSS.

**Comment by VictorChen** [comment]
ah cool, thanks!

**Comment by zhuyinjing** [comment]
you can get path elements.and setAttribute stroke : #D7217E
