### ISSUE TITLE
Leaflet 1.0 Compatibility

### ISSUE THREAD

**Issue by hrishiballal** [Wildhoney/Leaflet.FreeDraw#71]
When I use the latest release of FreeDraw with Leaflet 1.0 rc2, I am getting clipping errors especially in latLngsToClipperPoints. I can investigate more but I was wondering if this library is can be used with Leaflet 1.0?

**Comment by Wildhoney** [comment]
Sadly I need to update the module for 1.0 &mdash; definitely on the cards!

**Comment by hrishiballal** [comment]
Relevant API changes to Leaflet 1.0 taken from a [Leaflet.draw](https://github.com/Leaflet/Leaflet.draw/pull/596) bug.


- Polylines and Polygons may now use nested Arrays of LatLng objects. These correspond to deprecated MultiPolygons containing multiple "rings" where the first Array is the outer ring and all subsequent rings are subtracted inner rings (e.g. donut).
- The Polygon.getLatLngs() method now always returns a nested array of rings.
- Removed Polyline/Polygon spliceLatLngs method (use setLatLngs instead).
- Removed LatLng RAD_TO_DEG, DEG_TO_RAD, and MAX_MARGIN constants.

Other relevant internal API changes include:
- Polyline._projectLatLngs() no longer sets this._originalPoints array. Instead, it expects for array to be passed in (by reference) for Point objects to be assigned to.
- L.Marker._initInteraction() was rewritten (copied verbatim in src/ext/TouchEvents.js file).

**Comment by Wildhoney** [comment]
Thanks @hrishiballal &mdash; now Leaflet 1.0's been released, I'll make this a priority: https://github.com/Wildhoney/Leaflet.FreeDraw/issues/76
