### ISSUE TITLE
Map CSS is not working properly 

### ISSUE THREAD

**Issue by aartikanungo** [Wildhoney/Leaflet.FreeDraw#72]
section.map.mode-edit div.polygon-elbow {
    opacity: 1;
    pointer-events: all;
}

section.map.mode-create {
    cursor: crosshair !important;
}
these two sections are not working on my map..  except these two everything is working fine. any solution?

**Comment by Wildhoney** [comment]
Do you have a `section.map` node in your page?

**Comment by Wildhoney** [comment]
Please try with [`v2.0.0`](https://github.com/Wildhoney/Leaflet.FreeDraw).
