### ISSUE TITLE
Leaflet 1.0

### ISSUE THREAD

**Issue by Wildhoney** [Wildhoney/Leaflet.FreeDraw#76]
- Upgrade to Leaflet 1.0
- Remove D3 as a dependency
- Prevent event firing on zoom
- Support `WebWorker` for hull algorithm

**Comment by chriserickson** [comment]
Hello,
I was curious if you had any timeline regarding 1.0 support.

Thanks!

**Comment by Wildhoney** [comment]
It's [in progress](https://github.com/Wildhoney/Leaflet.FreeDraw/commits/v1) @chriserickson &ndash; please give me a week or two to write all the tests, update the docs, etc...

**Comment by chriserickson** [comment]
Great, thanks for the update!

**Comment by Wildhoney** [comment]
All released as `v2.0.0` 👍

I've tried my hardest to replicate the existing behaviour, but there are a number of changes which I've updated the README to reflect.

**Comment by knownasilya** [comment]
Is 2.0 backwards compat with Leaflet < 1.0?

**Comment by Wildhoney** [comment]
I haven't tested it, but I think support would be **very** limited as Leaflet 2 has removed `CLIP_PADDING` which means a huge amount of code to support clipped paths was removed from `v2.0.0`.
