### ISSUE TITLE
Rendering polygons that cover (0,0) renders as a SQUARE!

### ISSUE THREAD

**Issue by sinaru** [Wildhoney/Leaflet.FreeDraw#77]
When using `freeDraw.createPolygon(...)` method to render polygons that is covering to geo coordinates (0, 0) it renders as a **square**. 

```
this.freeDraw = new L.FreeDraw(mode: L.FreeDraw.MODES.VIEW)
...
var freeDrawPolygon = this.freeDraw.createPolygon(polygon.getLatLngs())
...
```

Here are results of printing latitude, longitude coordinates in two use cases. 

 Testing with a polygon of 5 points that is **not covering** (0,0) geo point:

`print(polygon.getLatLngs())`

> "LatLng(55.07837, -4.39453),LatLng(51.06902, -4.92187),LatLng(50.51343, -8.78906),LatLng(51.50874, -12.65625),LatLng(55.27912, -13.00781)"

`print(freeDrawPolygon._latlngs)`

> "LatLng(55.07837, -4.39453),LatLng(51.06902, -4.92187),LatLng(50.51343, -8.78906),LatLng(51.50874, -12.65625),LatLng(55.27912, -13.00781),LatLng(55.07837, -4.39453)"

**Note** freeDrawPolygon has 6 points (first, and last both same) to complete the square. This rendered correctly in the map.

 Testing with a polygon of 5 points that is **covering** (0,0) geo point:

`print(polygon.getLatLngs())`

> "LatLng(3.71078, 5.64697),LatLng(1.73557, 7.84424),LatLng(-1.75754, 6.45996),LatLng(-1.64772, -3.82324),LatLng(4.21494, -2.79053)"

`print(freeDrawPolygon._latlngs)`

> "LatLng(-0.75475, -1.37908),LatLng(0.75475, -1.37908),LatLng(0.75475, 1.37907),LatLng(-0.75475, 1.37907)"

**Note**  freeDrawPolygon has 4 points where it is expected 6 points, and also first and last is not equal, therefore in a way not complete. Also this rendered as a square near the (0,0).

**Comment by Wildhoney** [comment]
Please try with [`v2.0.0`](https://github.com/Wildhoney/Leaflet.FreeDraw).
