### ISSUE TITLE
Browserify Failed!: Cannot find module 'leaflet-freedraw'

### ISSUE THREAD

**Issue by njbarrett** [Wildhoney/Leaflet.FreeDraw#82]
Hey there,

Just trying to upgrade from a v1 to v2 today. I'm looking at the docs and it says to do

`import FreeDraw from 'leaflet-freedraw';`

However the module is called `leaflet.freedraw`.

When I change it to `import FreeDraw from 'leaflet.freedraw';` it's still not working however.

**Comment by Wildhoney** [comment]
Hey @njbarrett I've renamed the package to `leaflet-freedraw` as I'm not sure why I chose the period for the package name &ndash; in hindsight it seems odd. Please try again now and see if the issue persists.

**Comment by njbarrett** [comment]
@Wildhoney I am having this problem now:

```
import FreeDraw from 'leaflet-freedraw';

var freeDraw = new FreeDraw();
```

` _leafletFreedraw2.default is not a constructor`

**Comment by Wildhoney** [comment]
Sorry @njbarrett please try again. I think the [`browser` field](https://github.com/Wildhoney/Leaflet.FreeDraw/commit/c4be85e906f0396b04fe1f9e18c2497c42b29332#diff-b9cfc7f2cdf78a7f4b91a753d10865a2L6) was causing issues.

**Comment by njbarrett** [comment]
Hey thanks for your help @Wildhoney I am getting somewhere.

It's now saying:

`Browserify Failed!: Cannot find module 'L' from '/Users/nick/Sites/landguide/node_modules/leaflet-freedraw/dist'`

`Browserify Failed!: Cannot find module 'ClipperLib' from '/Users/nick/Sites/landguide/node_modules/leaflet-freedraw/dist'`

I do have leaflet as a dependency in my package.json
I'm not sure about ClipperLib ?

**Comment by Wildhoney** [comment]
Yep, install those (`npm i ramda leaflet clipper-lib`) as they are external dependencies. You'll need to `import L from 'leaflet'` above `import FreeDraw from 'leaflet-freedraw'`

**Comment by njbarrett** [comment]
Hey @Wildhoney 
I have installed those dependencies now. Same error.
Shouldn't browserify be looking for a module called `leaflet` and `clipper-lib` not `L` and `ClipperLib` ?

**Comment by Wildhoney** [comment]
Well in Webpack you can use the `resolve.alias` to setup the externals, and in Browserify there seems to be [Aliasify](https://github.com/benbria/aliasify) for this purpose.

I've [just changed](https://github.com/Wildhoney/Leaflet.FreeDraw/commit/2b7e4b34daf275ed7a5a0aaac80b2d35056a127e) the mapping in Webpack for the externals, so first please see if that helps without having to resort to Aliasify.

**Comment by njbarrett** [comment]
@Wildhoney That's done the trick! The bundle compiles successfully now.
One more problem...

`Uncaught ReferenceError: regeneratorRuntime is not defined`

and here's the context of the error from my inspector:

```
    /**
     * @method createPath
     * @param {Object} map
     * @param {Object} svg
     * @param {Point} fromPoint
     * @return {void}
     */

  }, {
    key: 'createPath',
    **value: regeneratorRuntime.mark(function createPath(map, svg, fromPoint) {**
      var lineFunction, toPoint, lineData;
      return regeneratorRuntime.wrap(function createPath$(_context) {
        while (1) {
          switch (_context.prev = _context.next) {
            case 0:

              // Define the line function to be used for the hand-drawn lines.
              lineFunction = (0, _d3Shape.line)().curve(_d3Shape.curveMonotoneX).x(function (d) {
                return d.x;
              }).y(function (d) {
                return d.y;
              });
```

Is this an issue with the transpiled file? From googling this looks like a possible fix... https://github.com/babel/babel/issues/2877#issuecomment-270700000

**Comment by Wildhoney** [comment]
That's good 👍 Yep, you're going to have to [apply Regenerator](https://github.com/amiorin/regeneratorify) to the bundle.

**Comment by njbarrett** [comment]
Thanks for your help @Wildhoney 
That regeneratorify didn't work, I don't think it's been updated in a long time.

I ended up switching the whole build process to webpack and have it all working now. I learnt a lot in the process too.

**Comment by Wildhoney** [comment]
Thankfully 👍 Although it's slightly annoying that we couldn't get it working with Browserify.

**Comment by njbarrett** [comment]
I'm sure it can be done, I know I was close.
Hopefully someone will find this on google and post if they got it working.

**Comment by jfolds** [comment]
Hello,
I'm running into the same error: `Uncaught ReferenceError: regeneratorRuntime is not defined`
I'm using webpack and importing like so:

```
import L from 'leaflet';
import FreeDraw from 'leaflet-freedraw';
```

Any help/suggestions would be very appreciated, thanks!

**Comment by njbarrett** [comment]
@jfolds what's your .babelrc look like ?
Try adding `"transform-runtime"` to the plugins array

**Comment by jfolds** [comment]
@njbarrett Thanks for the suggestion! I added that to my webpack.config in the babel-loader plugins, but still hitting that same error.

I needed a quick fix, so I am currently just requiring the JS rather than importing. Works for me... for now.
`require('leaflet-freedraw/dist/leaflet-freedraw.web.js');`

Thanks again for the help, though.

**Comment by kaffeeumeins** [comment]
I have the same problem and could solve it by importing also the babel-polyfill lib.
