### ISSUE TITLE
Changing styles dynamicaly

### ISSUE THREAD

**Issue by Dahkon** [Wildhoney/Leaflet.FreeDraw#83]
It would be nice to have a method to dynamicaly change default styles. 
We can change with javascript injecting style on the polygons but when a new one is drawn it automatically get the default style.
I'm sure I will find a solution but a native one would be better.

Thanks,

**Comment by Wildhoney** [comment]
Can you not use CSS for the styles? For example the demo's [polygon is styled with CSS](https://github.com/Wildhoney/Leaflet.FreeDraw/blob/master/example/css/default.css#L145-L150).

**Comment by Dahkon** [comment]
Not really, those styles are used by default but I use some sliders and colorpicker to change the polygons inline styles. This is working when the polygons are already drawn. But when I add a new one, all polygons get the default styles (css like in the demo).

I found a way but that's not a great solution, I use markers event to change all polygons styles.
So any action on polygons forces styles to be reinjected. That's working but a native solution would be better.

**Comment by Wildhoney** [comment]
Interestingly we could use CSS variables for something like this &ndash; [see the example I hastily put together](https://jsfiddle.net/tnaw1tm2/). Although of course [support](http://caniuse.com/#feat=css-variables) is the only weakness in such a solution.

I'm not entirely sure how a native solution would work, but I'll have a think.

**Comment by Dahkon** [comment]
Css variables would be awesome when Edge supports it... 

Maybe a function setStyle in the leafdraw object could do the job. Then each new polygon can be set to this default style if it's set, instead of the css stylesheet.

So far my solution is working anyway so no hurries for me.


Great plugin by the way.

**Comment by Wildhoney** [comment]
Thanks @Dahkon! I think we'll wait for CSS variables, as otherwise we'll end up taking the route down the rabbit hole, as I did with the previous version of the lib, which didn't quite work.
