### ISSUE TITLE
Missing build.js and leaflet.css

### ISSUE THREAD

**Issue by thomaslaine** [Wildhoney/Leaflet.FreeDraw#86]
Hello Adam, firstly thanks for your work. I got an issue. I'm sure it is on me, I don't understand or I forget to do something but I am stuck. When I launch the exemple build.js and leaflet.css are missing. I tried unsuccessfully to create them from your website or JSFiddle, it does not work.
Thank you for your input.

**Comment by Wildhoney** [comment]
Hmm, I'm not sure why `default.css` would be missing, but the `build.js` comes from the Webpack build.

Try [`npm run start`](https://github.com/Wildhoney/Leaflet.FreeDraw/blob/master/package.json#L10) which should `npm i`, build, and start the local web-server for you on [`localhost:5000`](http://localhost:5000/) 👍

**Comment by Wildhoney** [comment]
Did you fix this?
