### ISSUE TITLE
Uncaught ReferenceError: regeneratorRuntime is not defined

### ISSUE THREAD

**Issue by treyhakanson** [Wildhoney/Leaflet.FreeDraw#88]
Getting the following error in at leaflet-freedraw.cjs.js:734:

```
Uncaught ReferenceError: regeneratorRuntime is not defined.
```

I am only using es2015 stage-1 in my .babelrc, but I assume this shouldn't matter, as the library is using stage-3. I tried to use es2016 and stage-3 in my config just to be sure, and to no avail. Any ideas? Great job on the library by the way, I love the features you've put in!

**Comment by Wildhoney** [comment]
Thanks @treyhakanson!

You'll need either [`transform-regenerator`](https://babeljs.io/docs/plugins/transform-regenerator/) or the more general [`babel-polyfill`](https://babeljs.io/docs/usage/polyfill/) which includes it.

**Comment by treyhakanson** [comment]
`transform-regenerator` was giving me issues for some reason, but the following worked in my webpack config:

```js
module.exports = {
     entry: ['babel-polyfill', './app/index.js']
};
```

thanks!
