### ISSUE TITLE
load polygon

### ISSUE THREAD

**Issue by r2my** [Wildhoney/Leaflet.FreeDraw#91]
Hi,

I'm trying to load a polygon but I have an error.

I added the code below on default jsfiddle:
https://jsfiddle.net/t6e48rm5/
const polygons = freeDraw.create([
    new L.LatLng(51.50046151184328, -0.08771896362304689),
    new L.LatLng(51.50067523261736, -0.09175300598144533),
    new L.LatLng(51.50329323076107, -0.09106636047363283),
    new L.LatLng(51.50409462869737, -0.08763313293457033)
]);

Example there:
https://jsfiddle.net/jtqnhaeg/

Error is:
Uncaught TypeError: Cannot read property 'size' of undefined

Any idea?
Thank you very much.

Best regards,
Rémy

**Comment by r2my** [comment]
JS file updated, issue seems fixed. Thanks for this great plugin! :)

**Comment by Wildhoney** [comment]
Awesome! 😄

**Comment by roberts-g** [comment]
Hi, I'm currently having this problem, but can't seem to fix. I've tried downloading the most up to date js file, but I'm still getting the `Uncaught TypeError: Cannot read property 'size' of undefined`. 

Would someone mind showing me how to fix this/letting me know which file to download which fixes this?

**Comment by Wildhoney** [comment]
On which line is the error being thrown?

**Comment by roberts-g** [comment]
```
Uncaught TypeError: Cannot read property 'size' of undefined
    at createFor (leaflet-freedraw.web.js:2501)
    at FreeDraw.create (leaflet-freedraw.web.js:1839)
    at window.onload ((index):93)
```

So I imagine line 2501

**Comment by Wildhoney** [comment]
Can you replicate the problem in [the example](https://freedraw.herokuapp.com/). If so, how? If not, what are you doing differently?

**Comment by roberts-g** [comment]
Enter the following into the console on the example page:
```
const freeDraw = new FreeDraw();

freeDraw.create([
    new L.LatLng(51.50046151184328, -0.08771896362304689),
    new L.LatLng(51.50067523261736, -0.09175300598144533),
    new L.LatLng(51.50329323076107, -0.09106636047363283),
    new L.LatLng(51.50409462869737, -0.08763313293457033)
]);
```

This returns the error message:
```
Uncaught TypeError: Cannot read property 'size' of undefined
    at createFor (build.js:15755)
    at FreeDraw.create (build.js:15093)
    at <anonymous>:1:10
```

My understanding is that this should draw a polygon with elbows at the given four coordinates.

**Comment by Wildhoney** [comment]
You can't instantiate `FreeDraw` directly because in that case it's not tied to the map layer.

In the example try:

```javascript
// Remove the current example.
document.querySelector('section.map').remove();
const node = document.createElement('section');
node.classList.add('map');
document.body.appendChild(node);

// Reinitialise the map and add the FreeDraw layer.
const map = new L.Map(node, { doubleClickZoom: false }).setView([51.505, -0.09], 14);
const freeDraw = new FreeDraw({ mode: FreeDraw.ALL });
L.tileLayer('https://cartodb-basemaps-a.global.ssl.fastly.net/light_all/{z}/{x}/{y}@2x.png').addTo(map);
map.addLayer(freeDraw);

// Let's try...
freeDraw.create([
    new L.LatLng(51.50046151184328, -0.08771896362304689),
    new L.LatLng(51.50067523261736, -0.09175300598144533),
    new L.LatLng(51.50329323076107, -0.09106636047363283),
    new L.LatLng(51.50409462869737, -0.08763313293457033)
]);
```

**Comment by roberts-g** [comment]
Thank you! This fixed my problem.

**Comment by Wildhoney** [comment]
You're welcome! 👍

**Comment by stell** [comment]
This is not really an issue but maybe of interest for people having the same trouble.
I have a map which uses the cluster extension. When drawing the map is set the center and bounds of the map based on the cluster getBounds() and not by configuring the center.

I have this example: https://codepen.io/honk007/pen/oNXPGLb

When removing the center and centering afterwards based on cluster bounds or other stuff you get:
`Cannot read property 'size' of undefined`
