### ISSUE TITLE
Ability to specify you want to fire a 'markers' event when manually calling the create method

### ISSUE THREAD

**Issue by ventralnet** [Wildhoney/Leaflet.FreeDraw#92]
I would like to ability to have the create method fire a markers event if you use it to manually create a polygon.

**Comment by ventralnet** [comment]
It would be nice to be able to specify this for most of the API calls (such as remove and clear)

**Comment by Wildhoney** [comment]
If you manually create a polygon then you can also manually trigger the event using `freeDraw.mode(CREATE)`. Otherwise we'll be complicating the methods.
