### ISSUE TITLE
leaveModeAfterCreate option does not seem to work

### ISSUE THREAD

**Issue by aphilip17** [Wildhoney/Leaflet.FreeDraw#93]
Hi,
I set leaveModeAfterCreate to true. I would like to leave the CREATE mode after drawing.
I also tried in your JSFiddle.
https://jsfiddle.net/t6e48rm5/

Thank you

**Comment by Wildhoney** [comment]
[It seems to work](https://jsfiddle.net/t6e48rm5/66/) when you set `leaveModeAfterCreate` to `true`.

**Comment by aphilip17** [comment]
Okay my bad, it's because I was passing the leaveModeAfterCreate directly to an instance , instead of passing it to the its options.
Should have double-checked before posting it.

**Comment by Wildhoney** [comment]
👍
