### ISSUE TITLE
 _leafletFreedrawWeb2.default.default is not a constructor

### ISSUE THREAD

**Issue by zhuyinjing** [Wildhoney/Leaflet.FreeDraw#99]
when i use it `import FreeDraw from "leaflet-freedraw/dist/leaflet-freedraw.web.js";` in my project,it shows error:
` _leafletFreedrawWeb2.default.default is not a constructor`
how should i do?
and when i use `import FreeDraw from "leaflet-freedraw/dist/leaflet-freedraw.cjs.js`,it shows error:
` _leafletFreedrawCjs2.default.default is not a constructor`
and  `Uncaught ReferenceError: regeneratorRuntime is not defined`

**Comment by Wildhoney** [comment]
import FreeDraw from 'leaflet-freedraw' should work just fine.

For `regenerator-runtime` see: https://github.com/Wildhoney/Leaflet.FreeDraw/issues/88 👍 

Hope this helps.

**Comment by zhuyinjing** [comment]
oh..when i use `module.exports = {
  entry: {
    main: './src/main.js',
    entry: ['babel-polyfill', '../config/index.js']
  },`
it also shows error `regeneratorRuntime is not defined`
